---
apiVersion: v1
kind: Pod
metadata:
  name: apache-basic-auth-pod
  labels:
    app: apache-basic-auth
spec:
  subdomain: chart-web
  containers:
  - name: apache-basic-auth
    image: quay.io/pezhang/apache-basic-auth:latest
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: chart-web
spec:
  clusterIP: None
  selector:
    app: apache-basic-auth
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Namespace
metadata:
  name: helmrelease-secret-test
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
  namespace: helmrelease-secret-test
type: kubernetes.io/basic-auth
data:
  user: dXNlcg==
  password: cmVkaGF0
---
apiVersion: apps.open-cluster-management.io/v1
kind: HelmRelease
metadata:
  name: guestbook
  namespace: helmrelease-secret-test
repo:
  chartName: nginx-chart
  source:
    helmRepo:
      urls:
        - http://chart-web:8080/helm/nginx-chart-0.1.0.tgz
    type: helmrepo
  version: 0.1.0
  secretRef:
    name: secret-basic-auth
    namespace: helmrelease-secret-test
